package spring.app.core;

public enum StepSelector {
    START,
    USER_MENU,
    USER_PASS_REVIEW,
    ADMIN_MENU,
    ADMIN_ADD_USER,
    ADMIN_REMOVE_USER,
    USER_TAKE_REVIEW_ADD_THEME,
    USER_PASS_REVIEW,
    USER_TAKE_REVIEW_ADD_DATE,
    USER_TAKE_REVIEW_CONFIRMATION
}
