package spring.app.core;

public enum StepSelector {
    START,
    USER_MENU,
    ADMIN_MENU,
    ADMIN_ADD_USER,
    ADMIN_REMOVE_USER,
    ADMIN_USERS_LIST,
    ADMIN_EDIT_REVIEW_GET_USER_LIST,
    ADMIN_EDIT_REVIEW_GET_THEME_LIST,
    ADMIN_EDIT_REVIEW_GET_REVIEW_LIST,
    ADMIN_EDIT_REVIEW_GET_REVIEW_INFO,
    ADMIN_EDIT_REVIEW_CHANGE_REVIEW,
    USER_TAKE_REVIEW_ADD_THEME,
    USER_TAKE_REVIEW_ADD_DATE,
    USER_TAKE_REVIEW_CONFIRMATION,
    USER_PASS_REVIEW_ADD_THEME,
    USER_PASS_REVIEW_GET_LIST_REVIEW,
    USER_PASS_REVIEW_ADD_STUDENT_REVIEW,
    USER_CANCEL_REVIEW,
    USER_START_REVIEW_HANGOUTS_LINK,
    USER_START_REVIEW_RULES,
    USER_START_REVIEW_CORE
}
