package spring.app.core;

public enum StepSelector {
    START,
    USER_MENU,
    ADMIN_MENU,
    ADMIN_ADD_USER,
    ADMIN_REMOVE_USER,
    ADMIN_USERS_LIST,
    USER_TAKE_REVIEW_ADD_THEME,
    USER_TAKE_REVIEW_ADD_DATE,
    USER_TAKE_REVIEW_CONFIRMATION,
    USER_PASS_REVIEW_ADD_THEME,
    USER_PASS_REVIEW_GET_LIST_REVIEW,
    USER_PASS_REVIEW_ADD_STUDENT_REVIEW,
    USER_CANCEL_REVIEW
}
